# version of docker-compose
version: '3.6'

# list of containers
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"    
    volumes:
      - ./server/database/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  server:
    image: "node:18-alpine"
    user: "node"
    depends_on:
      - db
    environment:
      - NODE_ENV=development
    working_dir: /home/server
    volumes:
      - ./server:/home/server
    ports:
      - "8080:8080"
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run migrate
        node ./app.js

    # command: /bin/sh -c "./startup_script.sh"

  web:
    image: nginx
    depends_on:
      - db
      - server
    ports:
      - "80:80"
    volumes:
      - ./web/build:/home/www
      - ./web/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./web/conf/proxy.conf:/etc/nginx/proxy.conf